version: '3.8'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-server-db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=multipass

  db:
    image: postgres:14.4-alpine
    container_name: stats-server-db-container
    ports:
      - "6431:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=multipass